applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [

    # path(
    #     'entradas_general/', 
    #     views.EntryListViewBySearch.as_view(),
    #     name='entry-lista-general',
    # ),
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
    path(
        'agregar/', 
        views.AgregarEntradaCreateView.as_view(),
        name='add-entrada',
    ),

    path(
        'actualizar/<pk>/', 
        views.ActualizarEntradaUpdateView.as_view(),
        name='update-entrada',
    ),

]

applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil', 
        views.UserPageView.as_view(),
        name='perfil',
    ),   
    path(
        'add-entrada/<pk>', 
        views.AddFavoritosView.as_view(),
        name='add-favoritos',
    ),   
    path(
        'delete-favorites/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),   

]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
        path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/favoritos/models.py
from django.db import models
from django.conf import settings

# apps de terceros
from model_utils.models import TimeStampedModel

#
from applications.entrada.models import Entry

#
from .managers import FavoritesManager

class Favorites(TimeStampedModel):
    """ Modelo para favotios """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE,
    )
    entry = models.ForeignKey(
        Entry,
        related_name='entry_favorites',
        on_delete=models.CASCADE
    )

    objects = FavoritesManager()

    class Meta:
        unique_together = ('user', 'entry')
        verbose_name = 'Entrada Favorita'
        verbose_name_plural = 'Entradas Favoritas'
    
    def __str__(self):
        return self.entry.title

applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    # TIPO DE USUARIOS
    ADMINISTRADOR = '0'
    USUARIO = '1'
    OTRO = '2'
    # GENEROS
    VARON = 'M'
    MUJER = 'F'
    OTRO = 'O'
    #

    OCUPATION_CHOICES  = (
        (ADMINISTRADOR, 'Administrador'),
        (USUARIO, 'Usuario'),
        (OTRO, 'Otro'),
    )

    GENDER_CHOICES = (
        (VARON, 'Masculino'),
        (MUJER, 'Femenino'),
        (OTRO, 'Otros'),
    )

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    # ocupation = models.CharField(
    #     'Ocupacion',
    #     max_length=30, 
    #     blank=True
    # )
    ocupation = models.CharField(
        max_length=1, 
        choices=OCUPATION_CHOICES, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name',]

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

applications/favoritos/views.py
from django.urls import reverse_lazy,reverse

from django.http import HttpResponseRedirect 

from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import(
    ListView,
    View,
    DeleteView,

) 
from .models import Favorites

from applications.entrada.models import Entry
#
from applications.users.mixins import (
    AdministradorPermisoMixin,
    UsuarioPermisoMixin,
)

class UserPageView(ListView):

    template_name = "favoritos/perfil.html"
    context_object_name = 'entradas_user'
    login_url=reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return Favorites.objects.entradas_user(self.request.user)

class AddFavoritosView(UsuarioPermisoMixin,View):

    def post(self,request,*args,**kwargs):
        #recuperar el usuario
        usuario=self.request.user
        entrada= Entry.objects.get(id=self.kwargs['pk'])
        #registramos favoritos

        Favorites.objects.get_or_create(
            user=usuario,
            entry=entrada,
        )
        return HttpResponseRedirect(
            reverse(
                'favoritos_app:perfil',
            )
        )

class FavoritesDeleteView(UsuarioPermisoMixin,DeleteView):
    
    model = Favorites
    success_url='.'
    success_url=reverse_lazy('favoritos_app:perfil')


"""
from applications.favoritos.models import *
Favorites.objects.
"""

templates/favoritos/base_favoritos.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/estilos.css' %}">

{% endblock css %}

{% block js %}

{% endblock js %}

templates/favoritos/perfil.html
<!-- head para PC -->
{% extends "favoritos/base_favoritos.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container" style="min-height: 650px">
    <div class="row justify-content-center">
        <div class="col-sm-3 mt-4 px-4 py-4  bg-info">
            <div class="card1  text-white">
                <div class="card-body">
                    <div class="col">
                        <h5>{{user.full_name}}</h5>
                    </div>
                    <div class="col">
                        <p>{{user.email}}</p>
                    </div>
                    <div class="col">
                        <!-- <p>{{user.ocupation}}</p> -->
                        <p>{{user.get_ocupation_display }}</p>
                    </div>
                    <div class="col">
                        <p>{{user.date_birth}}</p>
                    </div>

                </div>
                <div class="col-12">
                        {% if not user.is_superuser %}
 
                            <span hidden="hidden"></span>

                        {% else %}
                        <p>
                            <a class=" btn btn-dark btn-block h5 text-light" href="{% url 'users_app:user-lista' %}">Listar Usuarios</a>
                        </p>
                        {% endif %}
                </div>
                    <div class="col-12">

                        <p>
                            <a class=" btn btn-warning btn-block h5 text-dark" href="{% url 'users_app:user-update' %}">Cambiar Contraseña</a>
                        </p>
                        <!-- <p ><a class=" btn btn-danger btn-block h5 text-white" href="{% url 'users_app:user-logout' %}" class="h5">Salir</a></p> -->
                    </div>
            </div>
        </div>
        <div class="col-sm-9 mt-3">
            <div class="row  px-3 py-3 ">
                {% for entrada in entradas_user %}
                        <div class="card1 mb-2 border" >
                            <div class="row justify-content-center align-items-center">
                              <div class="col-md-4">
                                <img class="img-fluid mt-4 d-block"  src="{{entrada.entry.image.url}}">
                              </div>
                              <div class="col-md-8">
                                <div class="card-fluid mb-2 mt-2">
                                  <h5 class="card-title">{{entrada.entry.title | truncatechars:100}}</h5>
                                  <p class="card-text">{{entrada.entry.resume | truncatechars:100}}</p>
                                  <div class="row mt-4 mr-0 ml-0">
                                    <div class="col-6">
                                        <a href="{% url 'entrada_app:entry-detail' entrada.entry.slug %}" class="btn btn-block btn-primary ">Ver</a>
                                    </div>
                                    <div class="col-6">
                                        <form method="post" action="{% url 'favoritos_app:delete-favoritos' entrada.id %}">{% csrf_token %}
                                            <button type="submit" class="btn btn-block btn-danger ">Eliminar</button>
                                        </form>
                                    </div>
                                </div>
                                </div>
                              </div>
                            </div>
                        </div>   
                {% endfor %}
            </div>
        </div>
 </div>       
</div>


{% endblock content %}