applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [

    # path(
    #     'entradas_general/', 
    #     views.EntryListViewBySearch.as_view(),
    #     name='entry-lista-general',
    # ),
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
    path(
        'agregar/', 
        views.AgregarEntradaCreateView.as_view(),
        name='add-entrada',
    ),

    path(
        'actualizar/<pk>/', 
        views.ActualizarEntradaUpdateView.as_view(),
        name='update-entrada',
    ),

]

applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil', 
        views.UserPageView.as_view(),
        name='perfil',
    ),   
    path(
        'add-entrada/<pk>', 
        views.AddFavoritosView.as_view(),
        name='add-favoritos',
    ),   
    path(
        'delete-favorites/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),   

]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"


urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),  

    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ),  
        path(
        'rcontact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),  
] 

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
        path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<div class="container">
  <div class="row mb-4 justify-content-center px-4 py-4" >
      <div class="col col-sm-8 col-lg-7 order-first bg-primary ">
        <div class="div px-4">

          <form class="mb-4" method="post" action="{% url 'home_app:add-contact' %}">{% csrf_token %}
            <h1 class="mb-4 display-4 h2 text-center text-white">Envia  un Mensaje</h1>
            <div class="row mb-4">
              <div class="col-6">
              <div class="form-outline mt-4">
                <p class="form-label text-light" for="">Nombres</p>
                <input type="text" name="full_name" id="id_full_name" class="form-control" placeholder="Ingresa tu Nombre">
              </div>
              </div>
              <div class="col-6">
              <div class="form-outline mt-4">
                <p class="form-label text-light" for="">Correo</p>
                <input type="email" name="email" id="id_email" class="form-control" placeholder="abc@gmail.com">
              </div>
              </div>
            </div>
            <div class="form-group mb-4">
              <p for="" class="text-light">Mensaje</p>
              <input type="text" class="form-control" name="messagge" id="id_messagge" placeholder="Escribe tu Mensaje" >
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-success btn-lg btn-block mt-2 text-center">Enviar</button>
            </div>
          </form>
        </div>
      </div>
      <div class="col-sm-4 col-lg-5 order-last ">
        <h1 class="mb-4 display-4 h2 text-center">Contacto</h1>
        <div class="col text-center " style="font-size: 18px;">
            <strong class="mb-4">Email: </strong><p class="">{{correo}}</p>
            <strong class="mb-4">Telefono: </strong><p class="">{{phone}}</p>
            <strong class="mb-4">Direccion: </strong><p class="">Lima, Peru</p>
            <br>
        </div>
      </div>
  </div>
</div>

templates/includes/header.html
{% load  static %}
<div class="row">
    <div class="col-12">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top ">
            <div class="container">
                <a class="navbar-brand d-sm-none d-lg-block" href="{% url 'home_app:index' %}"><img class="img-fluid " src="{% static 'img/logo2.jpg' %}" style="max-height: 3rem;"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-none d-md-block" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item  mx-1">
                        <a class="nav-link btn btn-outline-success text-white" href="{% url 'home_app:index' %}">Inicio<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item mx-1">
                        <a class="nav-link btn btn-outline-success text-white" href="{% url 'entrada_app:entry-lista' %}">Blog</a>
                    </li>
                    <li class="nav-item  mx-1">
                        {% if not user.is_anonymous %}
                        <a class="nav-link btn btn-outline-success text-white" href="{% url 'entrada_app:add-entrada' %}">Agregar<span class=""></span></a>
                        {% else %}
                        <span hidden="hidden">Error oculto</span>
                        {% endif %}
                    </li>
                    <li class="nav-item  mx-1">
                        {% if not user.is_anonymous %}
                        <a href="{% url 'favoritos_app:perfil' %}" class="nav-link btn btn-warning text-dark">Perfil</a>
                        {% else %}
                        <a href="{% url 'users_app:user-login' %}" class="nav-link btn btn-success text-white">Iniciar Sesion</a>
                        {% endif %}
                    </li>
                    <li class="nav-item mx-1">
                        {% if not user.is_anonymous %}
                        <a href="{% url 'users_app:user-logout' %}"  class="nav-link btn btn-danger text-white ">Salir</a>

                        {% endif %}
                    </li>

                        {% if not user.is_anonymous %}
                        <li class="nav-item mx-1">
                            <a class="nav-link text-white" href="{% url 'favoritos_app:perfil' %}">{{user.full_name}}</a>
                        </li>
                            {% else %}
                            <li class="nav-item mx-1">
                            <a class="nav-link btn text-white" href="{% url 'users_app:user-login' %}">Usuario: Anonimo</a>
                        </li>
                            {% endif %}
 
                    </ul>

                    <form method="get" action="{% url 'entrada_app:entry-lista' %}" class="form-inline my-2 my-lg-0">{% csrf_token %}
                        <input class="form-control mr-sm-2" id="kword" name="kword" type="search" placeholder="Buscar" aria-label="Search" value="{{request.GET.kword}}">
                        <button class="btn btn-dark my-2 my-sm-0" type="submit">Buscar</button>
                    </form>

                </div>
            </div>
        </nav>
    </div>
</div>