applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [

    # path(
    #     'entradas_general/', 
    #     views.EntryListViewBySearch.as_view(),
    #     name='entry-lista-general',
    # ),
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
    path(
        'agregar/', 
        views.AgregarEntradaCreateView.as_view(),
        name='add-entrada',
    ),

    path(
        'actualizar/<pk>/', 
        views.ActualizarEntradaUpdateView.as_view(),
        name='update-entrada',
    ),

]

applications/favoritos/urls.py
#
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil', 
        views.UserPageView.as_view(),
        name='perfil',
    ),   
    path(
        'add-entrada/<pk>', 
        views.AddFavoritosView.as_view(),
        name='add-favoritos',
    ),   
    path(
        'delete-favorites/<pk>', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favoritos',
    ),   

]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
        path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/entrada/models.py
# standard library
from datetime import timedelta, datetime
#
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
# apps de terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

#managers
from .managers import EntryManager


class Category(TimeStampedModel):
    """  Categorias de una entrada  """

    short_name = models.CharField(
        'Nombre corto', 
        max_length=30,
        unique=True
    )
    name = models.CharField(
        'Nombre', 
        max_length=30
    )

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
    
    def __str__(self):
        return self.name    


class Tag(TimeStampedModel):
    """ etiquetas de un articulo """

    name = models.CharField(
        'Nombre', 
        max_length=30
    )

    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Tags'
    
    def __str__(self):
        return self.name


class Entry(TimeStampedModel):
    """  modelo para entradas o articulos """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE
    )
    tag = models.ManyToManyField(Tag)
    title = models.CharField(
        'Titulo', 
        max_length=200
    )
    resume = models.CharField(
        'Resumen',
        max_length=400
        )

    content = RichTextUploadingField('contenido',config_name='special')
    public = models.BooleanField(default=False)
    image = models.ImageField(
        'Imagen', 
        upload_to='Entry',
    )
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    #
    slug = models.SlugField(editable=False, max_length=300)
    
    objects = EntryManager()

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'

    
    def __str__(self):
        return str(self.id) + '-' + self.title

    def get_absolute_url(self):
        return reverse_lazy(
            'entrada_app:entry-detail',
            kwargs={
                'slug': self.slug
            }
        )
    
    def save(self, *args, **kwargs):
        # calculamos el total de segundos de la hora actual
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))

        self.slug = slugify(slug_unique)

        super(Entry, self).save(*args, **kwargs)

applications/entrada/forms.py
from django  import forms

from .models import Entry
from applications.users.models import User

class EntradaForm(forms.ModelForm):

    class Meta:
        model = Entry
        #fields =(__all_)
        fields =(
        'user',
        'category',
        'tag',
        'title',
        'resume',
        'content',
        'public',
        'image',
        'portada',
        'in_home',
        )
        widgets={

            'user':forms.Select(
                attrs={
                'class':'form-control form-control-sm',

                }
            ),
            'category':forms.Select(
                attrs={
                'class':'form-control form-control-sm',
                }
            ),
            'public':forms.CheckboxInput(
                attrs={
                    'checked':'',
                }
            ),
            'in_home':forms.CheckboxInput(
                attrs={
                    'checked':'',
                }
            ),
            'title':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                }
            ),
            'tag':forms.SelectMultiple(
                attrs={

                    'class':'form-control form-control-sm w-85',
                }
            ),
            'resume':forms.Textarea(
                attrs={
                    'class':'form-control form-control-md',
                    'rows':'2',
                }
            ),

        }

applications/entrada/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from django.db.models import Q

from django.views.generic import(
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    View,
)
#
from .forms import EntradaForm

#
from .models import Entry,Category,Tag
#
from applications.users.mixins import (
    AdministradorPermisoMixin,
    UsuarioPermisoMixin,
)
# class BuscadorGeneralTemplateView(TemplateView):
#     template_name = "entrada/lista.html"

#     def get_context_data(self, **kwargs):
#         contexto_russell = super(BuscadorGeneralTemplateView, self).get_context_data(**kwargs)
#         #entradas recientes
#         contexto_russell['russell']=Entry.objects.buscador_general()
#         return contexto_russell

# class EntryListViewBySearch(ListView):
#     template_name = "entrada/lista.html"
#     context_object_name ='entradas'
#     paginate_by = 9

#     def get_context_data(self, **kwargs):
#         context = super(EntryListViewBySearch, self).get_context_data(**kwargs)
#         context['categorias']=Category.objects.all()

#         return context

#     def get_queryset(self):
#         kword_general= self.request.GET.get('kword_general','')
#         categoria= self.request.GET.get('categoria','')
#         #consulta de busqueda
#         resultado= Entry.objects.buscador_general(kword_general,categoria)

#         return resultado



class EntryListView(ListView):
    template_name = "entrada/lista.html"
    context_object_name ='entradas'
    paginate_by = 9
    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categorias']=Category.objects.all().order_by('name')

        return context
    
    #buscador input
    def get_queryset(self):
        kword= self.request.GET.get('kword','')
        categoria= self.request.GET.get('categoria','')
        #consulta de busqueda
        resultado= Entry.objects.buscar_entrada_categoria(kword,categoria)
        
        return resultado
class EntryDetailView(UsuarioPermisoMixin,DetailView):

    template_name ='entrada/detail.html'
    model = Entry


class AgregarEntradaCreateView(AdministradorPermisoMixin,CreateView):
    template_name = "entrada/agregar.html"
    form_class= EntradaForm
    success_url = '/'

    def form_valid(self, form):
        
        #logica del proceso
        entrada = form.save()
        #empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        entrada.save()
        return super(AgregarEntradaCreateView, self).form_valid(form)


class ActualizarEntradaUpdateView(AdministradorPermisoMixin,UpdateView):
    template_name = "entrada/actualizar.html"
    model=Entry
    form_class= EntradaForm
    reverse_lazy = 'entrada_app:entry-lista/'
        
    def form_valid(self, form):

        return super(ActualizarEntradaUpdateView, self).form_valid(form)


def buscador_general(request):
    queryset=request.GET.get('kword_general')
    print(queryset)
    resultado=Entry.objects.filter(public=True)
    if queryset:
        resultado=Entry.objects.filter(
            Q(title__icontains=resultado) |
            Q(resume__icontains=resultado)
    ).distinct
    print(resultado)
    return render(request,'entrada/lista.html',{'resultado':resultado})

templates/entrada/actualizar.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block content %}
{% include "includes/header.html" %}


<div class="container text-light " >
    <!-- <div class="row bg-primary mt-2 mb-2 justify-content-center " > -->
        <div class="row mb-4 mt-4">
            <div class="col-2 d-none d-sm-block d-md-none d-lg-block">

            </div>
        <div class="col-lg-8 bg-primary">
    <form class=" mt-2 mb-2 "  method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="col-12 mt-4 mb-4 ">
            <p class="h3 text-center">Modificar Post</p>
        </div>   
            <div class="form-row  mb-4 justify-content-center text-light">
                <div class="col-2">
                    <p>In Home:</p>
                    {{form.in_home}}
                </div>
                <div class="col-2">
                    <p>Publico:</p>
                    {{form.public}}
                </div>
                <div class="col-2">
                    <p>Portada:</p>
                    {{form.portada}}
                </div>
                <div class="col-5">
                    {{form.tag}}
                </div>
            </div>
            
            <div class="form-row justify-content-center">
                <div class="col-6">
                    <p>usuario</p>
                    {{form.user}}
                </div>
                <div class="col-6">
                    <p>categoria</p>
                    {{form.category}}
                </div>
                    <div class="col-6">
                        <p>titulo</p>
                        {{form.title}}
                    </div>
                    <div class="col-6">
                        <p>resumen</p>
                        {{form.resume}}
                    </div>
                <div class="col-12">
                    <h5>Contenido</h5>
                    {{form.media}}
                    {{form.content}}
                </div>
                <div class="col 12">
                    <p>Imagen</p>
                    {{form.image}}
                </div>
            </div>
            <div class="form-row">
                <div class="col-12  mt-4 mb-4 text-center">
                    <button type="submit" class=" text-white btn btn-success btn-block">Guardar</button>
                </div>
            </div>
    </form>
    </div>
    <div class="col-2 d-none d-sm-block d-md-none d-lg-block">
            
    </div>
    </div>
</div>


{% endblock content %}

templates/entrada/agregar.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block content %}
{% include "includes/header.html" %}

<div class="container text-light " style="min-height: 600px">
    <div class="row mb-4 mt-4">
            <div class="col-2 d-none d-sm-block d-md-none d-lg-block">
            </div>
        <div class="col-lg-8 bg-primary">
            <form class=" mt-2 mb-2"   method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="col-12 mt-4 mb-4 ">
                    <p class="h3 text-center">Agregar Nuevo Post</p>
                </div>
                <div class="col-12 form-row  mb-4 justify-content-center">
                        <div class="col-2">
                            <p>In Home:</p>
                            {{form.in_home}}
                        </div>
                        <div class="col-2">
                            <p>Publico:</p>
                            {{form.public}}
                        </div>
                        <div class="col-2">
                            <p>Portada:</p>
                            {{form.portada}}
                        </div>
                        <div class="col-5">
                            <select name="tag" class="form-control form-control-sm w-85" required="" id="id_tag" multiple="">
                                <option value="1" selected="selected">Programacion en Python</option>

                            </select>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="col-6">
                            <p>usuario</p>
                            <select name="user" class="form-control form-control-sm" required="" id="id_user">
                                <option value="6">prueba2@gmail.com</option>
                            
                                <option value="7">prueba3@gmail.com</option>
                            
                                <option value="5">prueba1@gmail.com</option>
                            
                                <option value="1" selected="selected" >roberthbardales@gmail.com</option>
                            
                            </select>
                        </div>
                        <div class="col-6">
                            <p>categoria</p>
                            <select name="category" class="form-control form-control-sm" required="" id="id_category">

                                <option value="4">JavaScript</option>
                            
                                <option value="1" selected="selected">Python</option>
                            
                                <option value="2">Postgresql</option>
                            
                                <option value="3">GitHub</option>
                            
                                <option value="9">hacking</option>
                            
                                <option value="12">TIPS Django</option>
                            
                                <option value="5">Django Basico</option>
                            
                                <option value="10">Django Usuarios</option>
                            
                                <option value="11">DJ M.Avanzados</option>
                            
                                <option value="6">Rest Framework</option>
                            
                            </select>
                        </div>
                            <div class="col-6">
                                <p>titulo</p>
                                {{form.title}}
                            </div>
                            <div class="col-6">
                                <p>resumen</p>
                                {{form.resume}}
                            </div>
                        <div class="col-12">
                            <h5>Contenido</h5>
                            {{form.media}}
                            {{form.content}}
                        </div>
                        <div class="col 12">
                            <p>Imagen</p>
                            {{form.image}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12  mt-4 mb-4 text-center">
                            <button type="submit" class=" text-white btn btn-success btn-block">Guardar</button>
                        </div>
                    </div>
            </form>
        </div>
        <div class="col-2 d-none d-sm-block d-md-none d-lg-block">

        </div>
    </div>
    <!-- </div> -->
</div>

{% endblock content %}

templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/entrada/detail.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block title %}
{{ entry.title }}
{% endblock title %}


{% block description %}
<meta name="description" content="{{ entry.resume }}">
{% endblock description %}
{% block tags %}
<meta name="keywords" content="
    {% for t in entry.tag.all %}
        {{ t.name }} ,
    {% endfor %}
">
{% endblock tags %}

{% block content %}

{% include "includes/header.html" %}

<div class="container">
    <div class="row mt-4">
        <div class="col-sm-10 col-md-10">
            <div class="col-12 mb-4 border-primary">
                <h2 class="text-center text-primary ">
                    {{ object.title }}
                </h2>
            </div>
                <div class="card-1  bienvenido text-white">
                    <div class="card-body bg-primary">
                    <p >{{ entry.resume }}</p>
                    </div>
                </div>
            <div class="col-12 mt-4 mb-4 border border-primary" style="min-height: 550px">
                <p><small class="text-secondary ">Creado: {{ entry.created}}</small></p>

                <p class="text-justify">
                    {{ entry.content |safe }}
                </p>
                    <small class="text-secondary">Modificado: {{ entry.modified}}</small><br>
            </div>

        </div>
        <div class="col-sm-2 col-md-2">
            <div class="col-12 ">
                <p class="h5">{{ entry.category }}</p>
                <img class="card-img-top " src="{{ entry.image.url }}" style="min-height: 5rem">
            </div>
            <div class="col-sm-12">
                {% if not user.is_anonymous %}
                <div class="card-body mb-2 mt-2 px-1 py-1">
                    <form class="blog-action " action="{% url 'favoritos_app:add-favoritos' entry.id %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-block btn- btn-primary text-white">Añadir</button>
                    </form>
                </div>
                {% else %}
                <div class="card-body mt-3 mb-3 mt-1 px-1 py-1">
                        <a class="btn btn-primary  btn-block btn-lg text-white" href="{% url 'users_app:user-register'%}">Registrate</a>
                    </div>
                {% endif %}
            </div>
            {% if not user.is_anonymous %}
            <div class="col-12">
                <div class="card-body mb-2 mt-2 px-1 py-1">
                    <a href="{% url 'entrada_app:update-entrada' entry.id %}" class="btn btn-block btn- btn-success text-white">Modificar</a>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}

templates/entrada/error raro.html
    <WordsStyle name="NUMBER" styleID="4" fgColor="8CD0D3" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATORS" styleID="5" fgColor="9F9D6D" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="IDENTIFIERS" styleID="6" fgColor="FFCFAF" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="DOUBLE QUOTED STRING" styleID="7" fgColor="CC9393" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING WITH THREE DOUBLE QUOTES" styleID="8" fgColor="CC9393" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="KEYWORD" styleID="9" fgColor="DFC47D" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="FILTER" styleID="10" fgColor="CEDF99" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="instre2" />
            <WordsStyle name="PLUGIN" styleID="11" fgColor="DCA3A3" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="type1" />
            <WordsStyle name="FUNCTION" styleID="12" fgColor="E3CEAB" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type2" />
            <WordsStyle name="CLIP PROPERTIES" styleID="13" fgColor="DCDCCC" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" keywordClass="type3" />
            <WordsStyle name="USER DEFINED" styleID="14" fgColor="FFEBDD" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" keywordClass="type4" />
        </LexerType>
        <LexerType name="baanc" desc="BaanC" ext="">
            <WordsStyle name="DEFAULT" styleID="0" fgColor="DCDCCC" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMMENT" styleID="1" fgColor="7F9F7F" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" />
            <WordsStyle name="COMMENT DOC" styleID="2" fgColor="7F9F7F" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" />
            <WordsStyle name="NUMBER" styleID="3" fgColor="8CD0D3" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="KEYWORDS" styleID="4" fgColor="DFC47D" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="STRING" styleID="5" fgColor="CC9393" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="PREPROCESSOR" styleID="6" fgColor="FFCFAF" bgColor="3F3F3F" fon

templates/entrada/lista.html
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<!-- col-sm-4 col-lg-5 -->

<div class="container" style="min-height: 600px">
    <div class="row mb-4">
        <div class="col-12">
            <br>
            <p class="h4">
                Buscar Post
            </p> 
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4  col-sm-12 col-md-10">
            <div>
                    <form class="col-12" method="get">{% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" id="kword" name="kword" placeholder="Buscar..." value="{{request.GET.kword}}">
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-success" type="button" value="Buscar">
                            </div>
                        </div>
                    </form>
                </div>
                    <div class="row  row-cols-1 row-cols-lg-3 mt-0" >
                        {% for entrada in entradas %}
                        <div class="col mb-4 " style="font-size: 14px;">
                            <div class="card h-100 ">
                                <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">
                                    <img class="img-fluid" src="{{entrada.image.url}}"">
                                </a>
                                <div class="card-body ">
                                    <h5 class="card-title">
                                        <a href="{% url 'entrada_app:entry-detail' entrada.slug %}">{{entrada.title | truncatechars:100}}</a>
                                </h5>
                                <p>
                                    {{ entrada.resume | truncatechars:70 }}
                                </p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">{{ entrada.created }}</small>
                                </div>
                            </div>
                        </div>
                        {%empty%}
                        <h3 style="color:red;">No hay resultados</h3>
                        {% endfor %}
                    </div>
 
                <div class="col-12 mb-4">
                        <div class="row justify-content-center mb-4">
                            {% if is_paginated %}
                            <nav aria-label="..." >
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <!-- <a href="?page={{page_obj.previous_page_number}}">Atras</a> -->
                                        <a class="page-link" href="?{{ request.GET.urlencode }}&page={{page_obj.previous_page_number}}" tabindex="-1">Atras</a>
                                    </li>
                                    {% endif %}
                                    {% for pagina in paginator.page_range %}
                                    {% ifequal pagina page_obj.number %}
                                    <!-- <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li> -->
                                    <li class="page-item active">
                                        <a class="page-link" href="#!"> {{ pagina }}<span class="sr-only">(current)</span></a>
                                    </li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?{{ request.GET.urlencode }}&page={{pagina}}">{{ pagina }}</a></li>
                                    {% endifequal %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <!-- <a href="?page={{page_obj.next_page_number}}">Siguiente</a> -->
                                        <a class="page-link" href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Siguiente</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                </div>

        </div>
        <div class="col-xs-8  col-sm-12 c col-md-2">
                    <div class="list-group">
                        <a href="#!" class="list-group-item active">Categorias</a>
                        <a href="{% url 'entrada_app:entry-lista' %}" class="list-group-item list-group-item-action">Todo</a>
                        {% for categoria in categorias %}
                        <a href="?categoria={{categoria.short_name}}" class="list-group-item list-group-item-action">{{categoria.short_name}}</a>
                        {% endfor %}
                    </div>
            </div>
        </div>
    </div>

</div>

{% include "includes/footer.html" %}
{% endblock content %}