applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
        path(
        'users/lista/', 
        views.UserListView.as_view(),
        name='user-lista',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    # urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    # TIPO DE USUARIOS
    ADMINISTRADOR = '0'
    USUARIO = '1'
    OTRO = '2'
    # GENEROS
    VARON = 'M'
    MUJER = 'F'
    OTRO = 'O'
    #

    OCUPATION_CHOICES  = (
        (ADMINISTRADOR, 'Administrador'),
        (USUARIO, 'Usuario'),
        (OTRO, 'Otro'),
    )

    GENDER_CHOICES = (
        (VARON, 'Masculino'),
        (MUJER, 'Femenino'),
        (OTRO, 'Otros'),
    )

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    # ocupation = models.CharField(
    #     'Ocupacion',
    #     max_length=30, 
    #     blank=True
    # )
    ocupation = models.CharField(
        max_length=1, 
        choices=OCUPATION_CHOICES, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name',]

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña',
                'class':'form-control form-control-sm'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña',
                'class':'form-control form-control-sm',
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico ...',
                    'class':'form-control'
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'nombres ...',
                    'class':'form-control'
                }
            ),
            'ocupation': forms.Select(
                attrs={
                    'class':'form-control',       

                }
            ),
            'genero': forms.Select(
                attrs={
                    'placeholder': 'Genero ...',
                    'class':'form-control',          
                }
            ),
            'date_birth': forms.DateInput(
                attrs={
                    'type': 'date',
                    'class':'form-control'
                },
            ),
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo Electronico',
                'class':'form-control mr-sm-2',
            }
        )
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña',
                'class':'form-control mr-sm-2',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
            
        
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña Actual',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': ' ',
                'class':'form-control mr-sm-2',
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña Nueva',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': ' ',
                'class':'form-control mr-sm-2',
            }
        )
    )

    # def clean(self):
    #     cleaned_data = super(UpdatePasswordForm, self).clean()
    #     password1 = self.cleaned_data['password1']
    #     password2 = self.cleaned_data['password2']

    #     if not authenticate(email=password1, password=password2):
    #         raise forms.ValidationError('La Contraseña Ingresada no es Correecta')
            
        
    #     return self.cleaned_data

applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView,
    ListView,
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UpdatePasswordForm,
)
#
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],
            ocupation=form.cleaned_data['ocupation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('favoritos_app:perfil')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )

class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/cambiar_contraseña.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')
    
    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']

        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)
    
class UserListView(LoginRequiredMixin,ListView):
    template_name = "users/lista_usuarios.html"
    context_object_name = 'usuarios'
    success_url = reverse_lazy('entrada_app:entry-lista')
    login_url = reverse_lazy('entrada_app:entry-lista')

    def get_queryset(self):
        return User.objects.usuarios_sistema()
    

templates/users/base_users.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/users/cambiar_contraseña.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container" style="min-height: 637px;">
    <div class="row  w-100">
            
        <div class="col-12 mb-4">

        </div>
        <div class="col-12 mb-4">

        </div>
        <div class="col-lg-4 bg-primary offset-lg-4 mt-4">
            <form class=" mt-1 px-4 py-4 " method="post" enctype="multipart/form-data">{% csrf_token %}
                <h5 class="display-5  mb-4 h2 text-center text-white">Cambiar Password</h1>

                <p class=" text-white text-">Usuario : {{ user.email}}</p>
                <p></p>
                {{form.as_p}}

                <div class="text-center px-2 py-3">
                    <button type="submit" class="btn btn-warning btn-block" href="{% url 'users_app:user-update'%}">Cambiar Contraseña</button>
                </div>
            </form>
            </div>
        </div>

    </div>


{% endblock content %}

                    <!-- <p class="text-white ">
                        Usuario: {{user.get_full_name}}
                    </p>
                      <div class="col-12">

                      <div class="form-outline mt-4 mb-4">
                        <p class="form-label text-light mb-2 mt-4" >Contraseña Anterior:</p>
                        {{form.password1}}                        
                        <p class="form-label text-light mb-2 mt-4" >Contraseña Nueva</p>
                        {{form.password2}}                        
                      </div>
                    </div> -->

templates/users/lista_usuarios.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container" style="min-height: 637px;">
    <div class="row mt-4 mb-4 px-4 py-4 mx-auto w-100">
      <table class="table table-hover table-dark table-responsive-sm table-responsive-md table-responsive-mlg">
        
        <div class="col-12">
            <h3 class="text-dark text-center">Usuarios</h3>
        </div>
        <div class="col-12 mt-4 mb-4 ">
            <h5>Usuario Actual: </h5>
            <h5>{{user}}</h5>
        </div>
        <div class="col-12">
          <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Email</th>
                <th scope="col">Ocupacion</th>
                <th scope="col">Genero</th>
                <th scope="col">Fecha de Nacimiento</th>
                <th scope="col">Is_Staff</th>
                <th scope="col">Is_Active</th>
              </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
              <tr>
                <th scope="row">{{ usuario.id }}</th>
                <td>{{ usuario.full_name }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.get_ocupation_display }}</td>
                <td>{{ usuario.genero }}</td>
                <td>{{ usuario.date_birth }}</td>
                <td>{{ usuario.is_staff }}</td>
                <td>{{ usuario.is_active }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
    </div>
</div>
        
{% endblock content %}

                <!-- <div class="col-12">
                    <label class="text-white" for="id_email">Email:</label>
                    <input type="text" name="email" placeholder="Correo Electronico" class="form-control mr-sm-2" required="" id="id_email">
                </div>
                <div class="col-12">
                    <label class="text-white" for="id_password">Password:</label>
                    <input type="password" name="password" placeholder="contraseña" class="form-control mr-sm-2" required="" id="id_password">                
                </div> -->

templates/users/login.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container" style="min-height: 637px;">
    <div class="row  w-100">
        <div class="col-12 mb-4">
        </div>
        <div class="col-12 mb-4">
        </div>
        <div class="col-lg-4 bg-primary offset-lg-4 mt-4">
            <form class="mb-1 mt-1 px-4 py-4 " method="post" enctype="multipart/form-data">{% csrf_token %}
                <h5 class="display-5  h2 text-center text-white">Administrador de Blog</h5>
                    {{form.as_p}}
                    <div class="text-center px-2 py-3">
                        <input type="submit" class="btn btn-success btn-block" value="Ingresar" />
                    </div>
                    <div class="text-center px-2 py-1">
                        <a class="btn btn-warning btn-block" href="{% url 'users_app:user-register'%}">Registrar</a>
                    </div>
            </form>
        </div>

    </div>

</div>
        
{% endblock content %}

                <!-- <div class="col-12">
                    <label class="text-white" for="id_email">Email:</label>
                    <input type="text" name="email" placeholder="Correo Electronico" class="form-control mr-sm-2" required="" id="id_email">
                </div>
                <div class="col-12">
                    <label class="text-white" for="id_password">Password:</label>
                    <input type="password" name="password" placeholder="contraseña" class="form-control mr-sm-2" required="" id="id_password">                
                </div> -->

templates/users/register.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="container" style="min-height: 637px;">
    <div class="row  w-100">
            
        <div class="col-12 mb-4">

        </div>

    <div class="col-lg-6 bg-primary offset-lg-3 mb-4  text-light">

        <p class="display h2 mt-4 text-center">
            Ingrese sus Datos
        </p>
        <div class="col-12 mb-4 mt-4">
            <form class="form-contorl " method="post" enctype="multipart/form-data">{% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-md-12">
                    <p>Email:
                    </p>
                    {{ form.email }}
                    </div>
                    <div class="form-group col-md-6">
                    <p>Nombres:
                    </p>
                    {{ form.full_name }}
                    </div>
                    <div class="form-group col-md-6">
                    <p>Ocupacion:
                    </p>
                    <select name="ocupation" class="form-control" id="id_ocupation">
                        <option value="1" selected="selected">Usuario</option>
    
                      </select>
                    </div>
                    <div class="form-group col-md-6">
                    <p>Genero:
                    </p>
                    <select name="genero" placeholder="Genero ..." class="form-control" id="id_genero">

                        <option value="M" selected="selected" >Masculino</option>
                        <option value="F">Femenino</option>
                        <option value="O">Otros</option>
                      </select>
                    </div>
                    <div class="form-group col-md-6">
                    <p>Fecha Nacimiento:
                    </p>
                    {{ form.date_birth }}
                    </div>
                    <div class="form-group col-md-12">
                    <p>Contraseña:
                    </p>
                    {{ form.password1 }}
                    </div>
                    <div class="form-group col-md-12">
                    <p>Repetir Contraseña:
                    </p>
                    {{ form.password2 }}
                    {% for e in  form.password2.errors %}
                    <p style="color:red;">{{ e }}</p>
                    {% endfor %}
                    </div>
                    <div class="form-group col-md-12">
                        <button class="btn btn-success btn-block" type="submit">Registrar</button>
                    </div>
                </div>
            </form>
        </div>
</div>
</div>
</div>

{% endblock content %}